---
title: "Antwoord ELs Lommelen op vraag create_statistics van verschillen"
author: "Anja Leyman - Els Lommelen"
date: "26 mei 2020"
output: html_document
---


Els Lommelen
26 mei 2020 13:05 (9 dagen geleden)
aan mij

Hallo Anja,

**Als je interesse hebt in de gemiddelde toename/afname tussen periodes voor plots of reservaten, is de enige correcte manier inderdaad om eerst de verschillen te berekenen en daar statistiek op te doen.**
**Als je de resultaten voor periodes wil vergelijken, ga je eerder per periode statistieken doet en deze resultaten grafisch voorstellen (boxplotje), en dan puur beschrijvend een vergelijking maken tussen de perioden (dus de verschillende cijfers weergeven, geen verschillen proberen).**

Dus ok om **create_statistics** aan te passen.

Voor een extra functie **create_statistics_diff()** ben ik eerlijk gezegd **geen voorstander** omdat ik het gevoel heb dat deze overbodig gaat zijn (en mogelijk zelfs niet gebruikt gaat worden omdat gebruikers meestal pas op zoek gaan naar een andere functie als ze iets niet kunnen, en dit resultaat kunnen ze heel gemakkelijk bereiken door de 2 vaak gebruikte functies te combineren).  Zoals eerder al aangegeven: te veel functies maken het aanbod onoverzichtelijk.

Ik ben ook niet zeker of **een extra parameter 'type'** een goed idee zou zijn.  Een basisregel bij het maken van functies is: elke functie doet 1 ding, en dit moet je gemakkelijk in een korte zin kunnen beschrijven.  Bij het toevoegen van een functionaliteit 'type' zou dit niet meer het geval zijn: de basisfunctie zou statistieken berekenen, maar een extra parameter zou ineens bepalen dat de functie voor het berekenen van statistieken nog verschillen gaat berekenen.  Dit gaat het ook **wat verwarrend** maken voor de parameters: ofwel berekent die functie in dat geval enkel statistieken van verschillen, ofwel moet je nog een extra parameter toevoegen die aangeeft voor welke waarden verschillen berekenen en van welke statistieken genomen moeten worden.  Enfin, het wringt wat bij het afbakenen van wat de functie precies doet, en als dat voor ons al niet duidelijk is, gaat dat voor andere gebruikers nog moeilijker zijn om te begrijpen waarvoor de functie precies dient.
*
Ook heb ik het gevoel dat je met **een aantal kleine, eenvoudige functies** die je na elkaar kan uitvoeren, vaak meer flexibiliteit hebt dan 1 of 2 functies met veel toeters en bellen.  Die toeters en bellen kunnen wel helpen als het net is wat je nodig hebt (of voor zeer specifieke analyses), maar als je als gebruiker net een iets andere optie nodig hebt dan hetgeen ingebouwd is, is de functie meteen onbruikbaar.  Bovendien zijn de kleine flexibele functies voor de gebruiker ook transparanter: ik doe eerst dit, en dan dat (en gebruikers gaan zelf moeten nadenken wat ze willen doen, wat betekent dat ze beter weten waar ze mee bezig zijn).

Ik zal na de middag die **parameter level in create_statistics alvast aanpassen zodat year en period niet meer automatisch meegenomen worden**, voor de rest hoor ik het nog wel.  😉

Groetjes,
Els

---

😉
Op ma 25 mei 2020 om 16:16 schreef Els Lommelen <els.lommelen@inbo.be>:
Hallo Anja,

Juist ja:
- voor het eerste geval: we hadden overeengekomen dat year en period voor create_statistics() sowieso meegenomen moesten worden als groeperende variabelen, en om het de gebruiker gemakkelijk te maken, moet hij die niet expliciet vermelden (zie documentatie in help).  Dit is een puur praktische beslissing geweest en die is in principe gemakkelijk aan te passen.  (Kan er wel voor zorgen dat gebruikers foutief gegevens van meerdere periodes of jaren gaan groeperen als het niet de bedoeling is.)

- voor het tweede geval: compare_periods() moet kolom plot_id bevatten om op plotniveau voor ontbrekende gegevens jaartallen te kunnen invullen.  Hier zou een alternatief kunnen zijn dat de gebruiker zelf aangeeft op welke kolom de functie zich moet baseren om eventuele ontbrekende jaartallen aan te vullen.  Om het niet te moeilijk te maken, kan de default plot_id zijn (zodat ervaren gebruikers die mogelijkheid kunnen gebruiken terwijl beginnende gebruikers er zich niks van moeten aantrekken en we kunnen een eenvoudige foutmelding geven, moest een aanpassing nodig zijn).

Laat maar weten wat het moet zijn (of allebei?), een kleintje om dat even aan te passen.  Als je wil helpen, mag je altijd een voorzet geven voor de aanpassing van de documentatie.  Dat gaat nog het meeste werk zijn.  😉 

**(c) Anja:**
*Mij leek het - onafhankelijk van scripts zelf - het meest logische (meest statistisch correcte (??) ) om create_statistics als laatste stap te doen.**
**Dan verkrijg je ook een lci, uci van de verschillen.*

*Als je compare_periods als laatste stap neemt, dan ga je 2 gemiddeldes op bosreservaatsniveau van elkaar aftrekken, en idem dito dan voor de lci, uci. *

*Dus ik zou voorstander zijn van het eerste.*
*MAAR: zou het geen mogelijkheid zijn om een extra functie "create_statistics_diff" aan te maken, die de statistieken specifiek voor "verschillen" berekent?*
*OF: een extra variabele "type" die aangeeft of je een toestand dan wel een verschil wil berekenen. Bij VBI wordt dat ook zo gedaan (weliswaar obv mixed models, maar misschien kan enkel het idee van "type" hier overgenomen worden (?))*

*Ter info heb ik in bijlage het script van de VBI gestopt, met de daarin gebruikte functies: zie "My.ParametersMB" ...*
*!! enkel om je een idee te geven ...*

`
